### PR TITLE
Updating models

### PR DESCRIPTION
**Pull request by KyleSchoonover**
Currently in draft.  Creating in order to view early the changes.  Will convert to full PR once complete.

### CODE REVIEW

**Comment by KyleSchoonover** [comment]
I have updated some of the models to align with what is posted on the API Endpoints documentation.

**Comment by KyleSchoonover** [comment]
@jethrocarr If you get a chance to review, let me know if you have any questions or need changes.

**Review by jethrocarr — APPROVED** [review]
Thanks @KTSchoonover this is excellent PR. Had a read through and it all looks solid.

I'm curious, did you generate the model manually, or did you utilise a tool to parse our API and/or the documentation to generate the updates? I'm keen to get the models into a state where they are more easily maintained to minimise drift between the API and the client libs.

**Comment by KTSchoonover** [comment]
@jethrocarr This was all manual, based on the documentation.  In an idea world, I would have access to an OpenAPI 3.0 compliant swagger.  This way you could auto-generate the majority of these libraries and in multiple languages.  This would potentially allow you to make changes to the API's and have CICD publish updated SDKs.

For reference: [Swagger CodeGen](https://swagger.io/tools/swagger-codegen/)

**Comment by jethrocarr** [comment]
Agree, thanks. I've flagged this as something for us to investigate internally.

**Pull request merged**
