### PR TITLE
Migrated to .NET Standard 2.0 and .NET 6.0 for Test Project

### PR DESCRIPTION
**Pull request by KyleSchoonover**
This takes the project up to .NET standard 2.0, as well as updates the test project to use the latest Long Term Support (LTS) version of .NET.

Additional work:
[Following .Net coding standard by implementing the editorconfig](https://github.com/dotnet/runtime/blob/main/.editorconfig)
Migrated test project to use the Microsoft Testing Framework as support by .NET 6.0
Removed obsolete code (since it has been over a year since this package was last published, it felt safe to remove)

For Reference:
[.NET Framework lifecycle](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework)
[.NET Standard version support](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)

### CODE REVIEW

**Comment by KyleSchoonover** [comment]
@kvainer It would be great to get this package updated to support those who are trying to migrate to new versions of .NET.

**Comment by georgekliao** [comment]
Hi @KyleSchoonover. Thanks for putting this together; we're going to have one of our team members take a look and get back to you.

**Comment by KyleSchoonover** [comment]
@georgekliao I would like to get it updated with the latest models, but wanted to start with the stack being upgraded first.  So, if this is merged expect a follow up PR.

**Comment by jethrocarr** [comment]
hi @KyleSchoonover ,

Thanks so much for this comprehensive pull request. I've had a review and it looks fantastic. I'm going to merge it into master and make the required changes to our CI/CD pipeline for building and testing on .NET 6.0.

regards,
Jethro

**Pull request merged**
